import { Outfit } from 'next/font/google';

const mainFontFamily = Outfit({
  weight: '500',
  subsets: ['latin']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {  
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mainFontFamily.className}>{children}</body>
    </html>
  )
}
